[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.19.5"
  # Using native lightningcss binary via optional dependency installation
  # Avoid noisy npm output in CI
  NPM_FLAGS = "--no-audit --fund=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

