import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif } from "next/font/google";
import "./globals.css";
import SiteNavbar from "@/components/nav/site-navbar";
import Providers from "@/components/Providers";
import { Footer7 } from "@/components/ui/footer-7";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-noto-serif",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${notoSerif.className} antialiased`}>
        <Providers>
          <header className="absolute top-0 left-0 right-0 z-50 w-full bg-transparent">
            <div className="relative flex justify-center py-2 md:py-3">
              <SiteNavbar />
            </div>
          </header>
          <main>{children}</main>
          <footer className="border-t border-white/10 bg-background/60">
            <Footer7 />
          </footer>
        </Providers>
      </body>
    </html>
  );
}
