import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif } from "next/font/google";
import "./globals.css";
import SiteNavbar from "@/components/nav/site-navbar";
import Providers from "@/components/Providers";
import { Footer7 } from "@/components/ui/footer-7";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-noto-serif",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.jpeg",
    shortcut: "/logo.jpeg",
    apple: "/logo.jpeg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} ${notoSerif.className} antialiased`}>
        <Providers>
          <header className="absolute top-2 md:top-3 left-0 right-0 z-50 w-full bg-transparent">
            <div className="relative flex justify-center py-2 md:py-3">
              <SiteNavbar />
            </div>
          </header>
          {/* Reserve space so fixed nav does not overlap content */}
          <main className="pb-20 sm:pb-0 sm:pt-16">{children}</main>
          <footer className="border-t border-white/10 bg-background/60">
            <Footer7
              logo={{
                url: "/",
                src: "/logo.jpeg",
                alt: "Sree Sabari Sastha Seva Samithi",
                title: "Sree Sabari Sastha Seva Samithi",
              }}
            />
          </footer>
        </Providers>
      </body>
    </html>
  );
}
